"""Modelo de datos.

Todo se maneja por cantidades:
  Posición OC --(FacturaLinea.cantidad)--> Factura
  FacturaLinea --(PLLinea.cantidad)--> Packing list
  PLLinea --(GrupoCajasItem.cantidad_por_caja x GrupoCajas.num_cajas)--> Cajas
  Packing list --> Unidad de carga (contenedor, aéreo, LCL...) --> Embarque

Cada dominio en su archivo; aquí se reexportan todos los modelos para importar
con `from app.modelos import X`.
"""
from app.modelos.acceso import DesafioDosPasos, Rol, SesionUsuario, Usuario
from app.modelos.base import Cantidad, ahora, cant
from app.modelos.clasificacion import (
    AtributoAmbito,
    AtributoDef,
    AtributoOpcion,
    CategoriaProducto,
    ClaseMaterial,
    CondicionRegla,
    ControlCapitulo,
    DominioCapitulo,
    DominioClasificacion,
    FilaLoteOficial,
    FuenteOficial,
    HistorialClasificacion,
    IncisoNacional,
    LoteOficial,
    NodoArancel,
    NotaSAC,
    OverrideArancel,
    PaisArancel,
    PalabraClave,
    ReglaClasificacion,
    ReglaImpuesto,
    Regulacion,
    SinonimoBusqueda,
    SinonimoMaterial,
    TraduccionCatalogo,
    VersionDataset,
)
from app.modelos.compras import ImportacionOC, OrdenCompra, PerfilImportacion, PosicionOC
from app.modelos.empaque import (
    GrupoCajas,
    GrupoCajasItem,
    PackingList,
    PlantillaCaja,
    PLLinea,
    RecepcionLinea,
    TipoEmpaque,
    tipo_empaque_contiene,
)
from app.modelos.empresa import Organizacion
from app.modelos.facturacion import Archivo, Factura, FacturaLinea
from app.modelos.maestros import (
    AcuerdoComercial,
    Almacen,
    Articulo,
    CategoriaArticulo,
    Centro,
    Contacto,
    EscalaTalla,
    EstadoLiberacion,
    GrupoArticulo,
    Marca,
    Pais,
    Prepack,
    PrepackComponente,
    Proveedor,
    Sociedad,
    ValorLista,
    centro_puertos,
    proveedor_marcas,
    proveedor_sociedades,
)
from app.modelos.productos import PartidaPais, Producto, ProductoDocumento, ProductoFoto, ProductoVersion
from app.modelos.sistema import Alerta, Edicion, Historial, Idempotencia, Meta
from app.modelos.transporte import (
    Embarque,
    EventoEmbarque,
    PasoLeadTime,
    Puerto,
    RegionLeadTime,
    ReglaLeadTime,
    TipoUnidad,
    Transportista,
    UnidadCarga,
    transportista_sociedades,
)

__all__ = [
    "AcuerdoComercial",
    "ahora",
    "Alerta",
    "Almacen",
    "Archivo",
    "Articulo",
    "AtributoAmbito",
    "AtributoDef",
    "AtributoOpcion",
    "cant",
    "Cantidad",
    "CategoriaArticulo",
    "CategoriaProducto",
    "Centro",
    "centro_puertos",
    "ClaseMaterial",
    "CondicionRegla",
    "Contacto",
    "ControlCapitulo",
    "DesafioDosPasos",
    "DominioCapitulo",
    "DominioClasificacion",
    "Edicion",
    "Embarque",
    "EscalaTalla",
    "EstadoLiberacion",
    "EventoEmbarque",
    "Factura",
    "FacturaLinea",
    "FilaLoteOficial",
    "FuenteOficial",
    "GrupoArticulo",
    "GrupoCajas",
    "GrupoCajasItem",
    "Historial",
    "HistorialClasificacion",
    "Idempotencia",
    "ImportacionOC",
    "IncisoNacional",
    "LoteOficial",
    "Marca",
    "Meta",
    "NodoArancel",
    "NotaSAC",
    "OrdenCompra",
    "Organizacion",
    "OverrideArancel",
    "PackingList",
    "Pais",
    "PaisArancel",
    "PalabraClave",
    "PartidaPais",
    "PerfilImportacion",
    "PasoLeadTime",
    "PlantillaCaja",
    "PLLinea",
    "PosicionOC",
    "Prepack",
    "PrepackComponente",
    "Producto",
    "ProductoDocumento",
    "ProductoFoto",
    "ProductoVersion",
    "Proveedor",
    "proveedor_marcas",
    "proveedor_sociedades",
    "Puerto",
    "RecepcionLinea",
    "RegionLeadTime",
    "ReglaClasificacion",
    "ReglaImpuesto",
    "ReglaLeadTime",
    "Regulacion",
    "Rol",
    "SesionUsuario",
    "SinonimoBusqueda",
    "SinonimoMaterial",
    "Sociedad",
    "tipo_empaque_contiene",
    "TipoEmpaque",
    "TipoUnidad",
    "TraduccionCatalogo",
    "Transportista",
    "transportista_sociedades",
    "UnidadCarga",
    "ValorLista",
    "Usuario",
    "VersionDataset",
]
