"""Esquema base

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 19:12:56.222878
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acuerdos_comerciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('origenes', sa.String(length=400), nullable=False),
    sa.Column('destinos', sa.String(length=100), nullable=False),
    sa.Column('prueba', sa.String(length=200), nullable=True),
    sa.Column('nota', sa.String(length=300), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('escalas_talla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=True),
    sa.Column('regla', sa.String(length=15), nullable=False),
    sa.Column('factor', sa.Integer(), nullable=True),
    sa.Column('longitud', sa.Integer(), nullable=True),
    sa.Column('tallas', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('grupos_articulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=15), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=10), nullable=False),
    sa.Column('dias_extra', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('idempotencia',
    sa.Column('clave', sa.String(length=160), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('respuesta', sa.JSON(), nullable=True),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('meta',
    sa.Column('clave', sa.String(length=40), nullable=False),
    sa.Column('valor', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('notas_sac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ambito', sa.String(length=16), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('capitulos', sa.JSON(), nullable=False),
    sa.Column('claves', sa.JSON(), nullable=False),
    sa.Column('fuente', sa.String(length=12), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('paises_arancel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('digitos', sa.Integer(), nullable=False),
    sa.Column('mcca', sa.Boolean(), nullable=False),
    sa.Column('impuesto', sa.String(length=60), nullable=True),
    sa.Column('nota', sa.String(length=300), nullable=True),
    sa.Column('base_legal', sa.String(length=300), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso')
    )
    op.create_table('partidas_sac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=False),
    sa.Column('descripcion', sa.String(length=400), nullable=False),
    sa.Column('nota', sa.String(length=300), nullable=True),
    sa.Column('fuente', sa.String(length=12), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('pasos_leadtime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('hito', sa.String(length=15), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('prepacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('estilo', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estilo', 'color', 'codigo')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('id_fiscal', sa.String(length=40), nullable=True),
    sa.Column('pais', sa.String(length=2), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('contacto', sa.String(length=120), nullable=True),
    sa.Column('correos', sa.String(length=500), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('puertos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('pais', sa.String(length=2), nullable=False),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('regiones_leadtime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('predeterminada', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('reglas_leadtime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=True),
    sa.Column('pais', sa.String(length=2), nullable=True),
    sa.Column('puerto', sa.String(length=10), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('pasos', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('permisos', sa.JSON(), nullable=False),
    sa.Column('sistema', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('sociedades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('id_fiscal', sa.String(length=30), nullable=True),
    sa.Column('pais', sa.String(length=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('correos', sa.String(length=500), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('tipos_empaque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('prefijo', sa.String(length=6), nullable=True),
    sa.Column('cuenta_como', sa.String(length=10), nullable=False),
    sa.Column('uom', sa.String(length=10), nullable=True),
    sa.Column('largo', sa.Float(), nullable=True),
    sa.Column('ancho', sa.Float(), nullable=True),
    sa.Column('alto', sa.Float(), nullable=True),
    sa.Column('tara', sa.Float(), nullable=True),
    sa.Column('peso_max', sa.Float(), nullable=True),
    sa.Column('max_unidades', sa.Integer(), nullable=True),
    sa.Column('max_contenido', sa.Integer(), nullable=True),
    sa.Column('contiene_productos', sa.Boolean(), nullable=False),
    sa.Column('mezcla_productos', sa.Boolean(), nullable=False),
    sa.Column('mezcla_tallas', sa.Boolean(), nullable=False),
    sa.Column('mezcla_oc', sa.Boolean(), nullable=False),
    sa.Column('identificador', sa.String(length=15), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('tipos_unidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('modo', sa.String(length=12), nullable=False),
    sa.Column('modalidad', sa.String(length=10), nullable=False),
    sa.Column('capacidad_cbm', sa.Float(), nullable=True),
    sa.Column('capacidad_kg', sa.Float(), nullable=True),
    sa.Column('requiere_sello', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('transportistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('codigo_internacional', sa.String(length=10), nullable=True),
    sa.Column('id_fiscal', sa.String(length=40), nullable=True),
    sa.Column('pais', sa.String(length=2), nullable=True),
    sa.Column('contacto', sa.String(length=120), nullable=True),
    sa.Column('correos', sa.String(length=500), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=False),
    sa.Column('referencia', sa.JSON(), nullable=True),
    sa.Column('resuelta', sa.Boolean(), nullable=False),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('almacenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('sociedad_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sociedad_id'], ['sociedades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    with op.batch_alter_table('almacenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_almacenes_sociedad_id'), ['sociedad_id'], unique=False)

    op.create_table('centros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('sociedad_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('pais', sa.String(length=2), nullable=True),
    sa.Column('puerto', sa.String(length=10), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('correos', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sociedad_id'], ['sociedades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    with op.batch_alter_table('centros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_centros_sociedad_id'), ['sociedad_id'], unique=False)

    op.create_table('embarques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('tipo_transporte', sa.String(length=12), nullable=False),
    sa.Column('documento_numero', sa.String(length=50), nullable=True),
    sa.Column('transportista_id', sa.Integer(), nullable=True),
    sa.Column('transportista', sa.String(length=150), nullable=True),
    sa.Column('puerto_origen', sa.String(length=10), nullable=True),
    sa.Column('puerto_destino', sa.String(length=10), nullable=True),
    sa.Column('centro', sa.String(length=10), nullable=True),
    sa.Column('etd', sa.Date(), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('salida_real', sa.Date(), nullable=True),
    sa.Column('arribo_real', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transportista_id'], ['transportistas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('ordenes_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('sociedad', sa.String(length=10), nullable=True),
    sa.Column('centro', sa.String(length=10), nullable=True),
    sa.Column('centro_destino', sa.String(length=10), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('incoterm', sa.String(length=10), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('puerto_despacho', sa.String(length=10), nullable=True),
    sa.Column('pais_origen', sa.String(length=2), nullable=True),
    sa.Column('pais_procedencia', sa.String(length=2), nullable=True),
    sa.Column('fecha_xf_original', sa.Date(), nullable=True),
    sa.Column('fecha_xf', sa.Date(), nullable=True),
    sa.Column('fecha_tienda', sa.Date(), nullable=True),
    sa.Column('liberacion_comercial', sa.String(length=1), nullable=False),
    sa.Column('liberacion_logistica', sa.String(length=3), nullable=False),
    sa.Column('fecha_lib_comercial', sa.Date(), nullable=True),
    sa.Column('fecha_lib_logistica', sa.Date(), nullable=True),
    sa.Column('liberada', sa.Boolean(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proveedor_id', 'numero')
    )
    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordenes_compra_proveedor_id'), ['proveedor_id'], unique=False)

    op.create_table('plantillas_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cantidad_por_caja', sa.Integer(), nullable=False),
    sa.Column('unidad', sa.String(length=5), nullable=False),
    sa.Column('largo', sa.Float(), nullable=True),
    sa.Column('ancho', sa.Float(), nullable=True),
    sa.Column('alto', sa.Float(), nullable=True),
    sa.Column('tara', sa.Float(), nullable=True),
    sa.Column('tipo_empaque_id', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['tipo_empaque_id'], ['tipos_empaque.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proveedor_id', 'nombre')
    )
    with op.batch_alter_table('plantillas_caja', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plantillas_caja_proveedor_id'), ['proveedor_id'], unique=False)

    op.create_table('proveedor_marcas',
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proveedor_id', 'marca_id')
    )
    op.create_table('proveedor_sociedades',
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('sociedad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sociedad_id'], ['sociedades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proveedor_id', 'sociedad_id')
    )
    op.create_table('tipo_empaque_contiene',
    sa.Column('padre_id', sa.Integer(), nullable=False),
    sa.Column('hijo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hijo_id'], ['tipos_empaque.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['padre_id'], ['tipos_empaque.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('padre_id', 'hijo_id')
    )
    op.create_table('transportista_sociedades',
    sa.Column('transportista_id', sa.Integer(), nullable=False),
    sa.Column('sociedad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sociedad_id'], ['sociedades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transportista_id'], ['transportistas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transportista_id', 'sociedad_id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('dos_pasos', sa.Boolean(), nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('password_cambiado_en', sa.DateTime(), nullable=True),
    sa.Column('preferencias', sa.JSON(), nullable=False),
    sa.Column('foto', sa.Text(), nullable=True),
    sa.Column('cargo', sa.String(length=120), nullable=True),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('empresa', sa.String(length=200), nullable=True),
    sa.Column('clave_temporal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('centro_puertos',
    sa.Column('centro_id', sa.Integer(), nullable=False),
    sa.Column('puerto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['centro_id'], ['centros.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['puerto_id'], ['puertos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('centro_id', 'puerto_id')
    )
    op.create_table('clasif_palabras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frase', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('atributos', sa.JSON(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clasif_sinonimos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('palabra', sa.String(length=60), nullable=False),
    sa.Column('equivale', sa.String(length=30), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('palabra')
    )
    op.create_table('contactos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sociedad_id', sa.Integer(), nullable=True),
    sa.Column('centro_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('cargo', sa.String(length=120), nullable=True),
    sa.Column('rol', sa.String(length=15), nullable=False),
    sa.Column('correos', sa.String(length=500), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['centro_id'], ['centros.id'], ),
    sa.ForeignKeyConstraint(['sociedad_id'], ['sociedades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contactos_centro_id'), ['centro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contactos_sociedad_id'), ['sociedad_id'], unique=False)

    op.create_table('desafios_dos_pasos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('codigo_hash', sa.String(length=64), nullable=False),
    sa.Column('expira', sa.DateTime(), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('envios', sa.Integer(), nullable=False),
    sa.Column('ultimo_envio', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('desafios_dos_pasos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_desafios_dos_pasos_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('eventos_embarque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embarque_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('ubicacion', sa.String(length=150), nullable=True),
    sa.Column('observacion', sa.String(length=500), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['embarque_id'], ['embarques.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventos_embarque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_embarque_embarque_id'), ['embarque_id'], unique=False)

    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('incoterm', sa.String(length=10), nullable=True),
    sa.Column('sociedad', sa.String(length=10), nullable=False),
    sa.Column('centro', sa.String(length=10), nullable=True),
    sa.Column('centro_destino', sa.String(length=10), nullable=True),
    sa.Column('condiciones', sa.String(length=200), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('finalizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facturas_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_proveedor_id'), ['proveedor_id'], unique=False)
        batch_op.create_index('ux_factura_numero', ['proveedor_id', 'numero'], unique=True, sqlite_where=sa.text("numero IS NOT NULL AND estado <> 'CANCELADA'"), postgresql_where=sa.text("numero IS NOT NULL AND estado <> 'CANCELADA'"))

    op.create_table('historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad', sa.String(length=30), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('detalle', sa.JSON(), nullable=True),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historial', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historial_factura_id'), ['factura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historial_fecha'), ['fecha'], unique=False)

    op.create_table('importaciones_oc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nombre_archivo', sa.String(length=300), nullable=False),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('filas', sa.JSON(), nullable=False),
    sa.Column('resultado', sa.JSON(), nullable=True),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incisos_nacionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=2), nullable=False),
    sa.Column('codigo', sa.String(length=14), nullable=False),
    sa.Column('sub6', sa.String(length=6), nullable=False),
    sa.Column('cond', sa.JSON(), nullable=False),
    sa.Column('prio', sa.Integer(), nullable=False),
    sa.Column('dai', sa.String(length=10), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('nota', sa.String(length=300), nullable=True),
    sa.Column('fuente', sa.String(length=12), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incisos_nacionales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incisos_nacionales_pais'), ['pais'], unique=False)
        batch_op.create_index(batch_op.f('ix_incisos_nacionales_sub6'), ['sub6'], unique=False)

    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('estilo', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('codigo_generico', sa.String(length=40), nullable=True),
    sa.Column('unidad', sa.String(length=5), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('ficha', sa.JSON(), nullable=False),
    sa.Column('descripcion_aduana', sa.String(length=400), nullable=True),
    sa.Column('descripcion_comercial', sa.String(length=300), nullable=True),
    sa.Column('pais_origen', sa.String(length=2), nullable=True),
    sa.Column('pais_procedencia', sa.String(length=2), nullable=True),
    sa.Column('ficha_completa', sa.Boolean(), nullable=False),
    sa.Column('faltan', sa.JSON(), nullable=False),
    sa.Column('version_ficha', sa.Integer(), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('sugerido', sa.String(length=14), nullable=True),
    sa.Column('propuesta', sa.String(length=14), nullable=True),
    sa.Column('codigo', sa.String(length=14), nullable=True),
    sa.Column('confianza', sa.String(length=10), nullable=True),
    sa.Column('fuente', sa.String(length=12), nullable=True),
    sa.Column('perfil', sa.String(length=200), nullable=True),
    sa.Column('analisis', sa.JSON(), nullable=True),
    sa.Column('alertas_ok', sa.JSON(), nullable=False),
    sa.Column('observaciones', sa.String(length=2000), nullable=True),
    sa.Column('resolucion', sa.String(length=200), nullable=True),
    sa.Column('notas', sa.String(length=1000), nullable=True),
    sa.Column('opinion_ia', sa.JSON(), nullable=True),
    sa.Column('revisado_por_id', sa.Integer(), nullable=True),
    sa.Column('revisado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_articulos.id'], ),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['revisado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proveedor_id', 'estilo', 'color')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_actualizado_en'), ['actualizado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_codigo_generico'), ['codigo_generico'], unique=True)
        batch_op.create_index(batch_op.f('ix_productos_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_marca_id'), ['marca_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_proveedor_id'), ['proveedor_id'], unique=False)

    op.create_table('sesiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('creada', sa.DateTime(), nullable=False),
    sa.Column('expira', sa.DateTime(), nullable=False),
    sa.Column('ultima_actividad', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('agente', sa.String(length=300), nullable=True),
    sa.Column('revocada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('sesiones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesiones_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('unidades_carga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embarque_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('etiqueta', sa.String(length=30), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('sello', sa.String(length=30), nullable=True),
    sa.Column('capacidad_cbm', sa.Float(), nullable=True),
    sa.Column('capacidad_kg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['embarque_id'], ['embarques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unidades_carga', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unidades_carga_embarque_id'), ['embarque_id'], unique=False)

    op.create_table('archivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('ruta', sa.String(length=500), nullable=False),
    sa.Column('tamano', sa.Integer(), nullable=False),
    sa.Column('subido_por', sa.Integer(), nullable=True),
    sa.Column('subido_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['subido_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archivos_factura_id'), ['factura_id'], unique=False)

    op.create_table('articulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('generico', sa.String(length=40), nullable=True),
    sa.Column('sku_proveedor', sa.String(length=60), nullable=True),
    sa.Column('upc', sa.String(length=40), nullable=True),
    sa.Column('estilo', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('talla', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('unidad', sa.String(length=5), nullable=False),
    sa.Column('peso_unitario', sa.Float(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('prepack_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_articulos.id'], ),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
    sa.ForeignKeyConstraint(['prepack_id'], ['prepacks.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articulos_generico'), ['generico'], unique=False)
        batch_op.create_index(batch_op.f('ix_articulos_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articulos_marca_id'), ['marca_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articulos_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articulos_sku_proveedor'), ['sku_proveedor'], unique=False)

    op.create_table('packing_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('unidad_carga_id', sa.Integer(), nullable=True),
    sa.Column('asignacion', sa.String(length=12), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('recolectado_en', sa.Date(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['unidad_carga_id'], ['unidades_carga.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packing_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packing_lists_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_packing_lists_factura_id'), ['factura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_packing_lists_unidad_carga_id'), ['unidad_carga_id'], unique=False)

    op.create_table('partidas_pais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=2), nullable=False),
    sa.Column('codigo', sa.String(length=14), nullable=False),
    sa.Column('dai', sa.String(length=10), nullable=True),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('fuente', sa.String(length=12), nullable=True),
    sa.Column('manual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'pais')
    )
    with op.batch_alter_table('partidas_pais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partidas_pais_producto_id'), ['producto_id'], unique=False)

    op.create_table('producto_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('ruta', sa.String(length=500), nullable=False),
    sa.Column('tipo_mime', sa.String(length=60), nullable=False),
    sa.Column('tamano', sa.Integer(), nullable=False),
    sa.Column('subido_por', sa.Integer(), nullable=True),
    sa.Column('subido_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subido_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('producto_fotos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_producto_fotos_producto_id'), ['producto_id'], unique=False)

    op.create_table('producto_versiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('desde', sa.Date(), nullable=True),
    sa.Column('hasta', sa.Date(), nullable=True),
    sa.Column('motivo', sa.String(length=300), nullable=True),
    sa.Column('datos', sa.JSON(), nullable=False),
    sa.Column('cerrado_por', sa.Integer(), nullable=True),
    sa.Column('cerrado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cerrado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('producto_versiones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_producto_versiones_producto_id'), ['producto_id'], unique=False)

    op.create_table('grupos_cajas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pl_id', sa.Integer(), nullable=False),
    sa.Column('num_cajas', sa.Integer(), nullable=False),
    sa.Column('largo', sa.Float(), nullable=True),
    sa.Column('ancho', sa.Float(), nullable=True),
    sa.Column('alto', sa.Float(), nullable=True),
    sa.Column('peso_neto_caja', sa.Float(), nullable=True),
    sa.Column('peso_bruto_caja', sa.Float(), nullable=True),
    sa.Column('plantilla_id', sa.Integer(), nullable=True),
    sa.Column('plantilla_nombre', sa.String(length=100), nullable=True),
    sa.Column('es_parcial', sa.Boolean(), nullable=False),
    sa.Column('peso_estimado', sa.Boolean(), nullable=False),
    sa.Column('observacion', sa.String(length=300), nullable=True),
    sa.Column('tipo_empaque_id', sa.Integer(), nullable=True),
    sa.Column('padre_id', sa.Integer(), nullable=True),
    sa.Column('tara', sa.Float(), nullable=True),
    sa.Column('neto_manual', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['padre_id'], ['grupos_cajas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pl_id'], ['packing_lists.id'], ),
    sa.ForeignKeyConstraint(['plantilla_id'], ['plantillas_caja.id'], ),
    sa.ForeignKeyConstraint(['tipo_empaque_id'], ['tipos_empaque.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grupos_cajas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grupos_cajas_padre_id'), ['padre_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grupos_cajas_pl_id'), ['pl_id'], unique=False)

    op.create_table('posiciones_oc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oc_id', sa.Integer(), nullable=False),
    sa.Column('posicion', sa.String(length=10), nullable=False),
    sa.Column('almacen', sa.String(length=10), nullable=True),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.Column('codigo_sap', sa.String(length=40), nullable=False),
    sa.Column('upc', sa.String(length=40), nullable=True),
    sa.Column('estilo', sa.String(length=40), nullable=True),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('talla', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('marca', sa.String(length=10), nullable=True),
    sa.Column('grupo', sa.String(length=15), nullable=True),
    sa.Column('categoria', sa.String(length=10), nullable=True),
    sa.Column('tipo_empaque', sa.String(length=10), nullable=False),
    sa.Column('casepack', sa.Integer(), nullable=True),
    sa.Column('inner_pack', sa.Integer(), nullable=True),
    sa.Column('prepack', sa.String(length=30), nullable=True),
    sa.Column('unidades_por_caja', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('unidad', sa.String(length=5), nullable=False),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('pais_origen', sa.String(length=3), nullable=True),
    sa.Column('bloqueada', sa.Boolean(), nullable=False),
    sa.Column('motivo_bloqueo', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id'], ),
    sa.ForeignKeyConstraint(['oc_id'], ['ordenes_compra.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oc_id', 'posicion')
    )
    with op.batch_alter_table('posiciones_oc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posiciones_oc_articulo_id'), ['articulo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posiciones_oc_oc_id'), ['oc_id'], unique=False)

    op.create_table('prepack_componentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prepack_id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id'], ),
    sa.ForeignKeyConstraint(['prepack_id'], ['prepacks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prepack_id', 'articulo_id')
    )
    with op.batch_alter_table('prepack_componentes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prepack_componentes_prepack_id'), ['prepack_id'], unique=False)

    op.create_table('factura_lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('posicion_oc_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('precio_oc', sa.Float(), nullable=False),
    sa.Column('motivo_precio', sa.String(length=300), nullable=True),
    sa.Column('oc_numero', sa.String(length=30), nullable=False),
    sa.Column('almacen', sa.String(length=10), nullable=True),
    sa.Column('posicion', sa.String(length=10), nullable=False),
    sa.Column('codigo_sap', sa.String(length=40), nullable=False),
    sa.Column('upc', sa.String(length=40), nullable=True),
    sa.Column('estilo', sa.String(length=40), nullable=True),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('talla', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('unidad', sa.String(length=5), nullable=False),
    sa.Column('marca', sa.String(length=10), nullable=True),
    sa.Column('categoria', sa.String(length=10), nullable=True),
    sa.Column('tipo_empaque', sa.String(length=10), nullable=False),
    sa.Column('casepack', sa.Integer(), nullable=True),
    sa.Column('inner_pack', sa.Integer(), nullable=True),
    sa.Column('prepack', sa.String(length=30), nullable=True),
    sa.Column('unidades_por_caja', sa.Integer(), nullable=True),
    sa.Column('centro_destino', sa.String(length=10), nullable=True),
    sa.Column('pais_origen', sa.String(length=3), nullable=True),
    sa.Column('partida_arancelaria', sa.String(length=20), nullable=True),
    sa.Column('descripcion_comercial', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['posicion_oc_id'], ['posiciones_oc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factura_id', 'posicion_oc_id')
    )
    with op.batch_alter_table('factura_lineas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factura_lineas_factura_id'), ['factura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_factura_lineas_posicion_oc_id'), ['posicion_oc_id'], unique=False)

    op.create_table('pl_lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pl_id', sa.Integer(), nullable=False),
    sa.Column('factura_linea_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['factura_linea_id'], ['factura_lineas.id'], ),
    sa.ForeignKeyConstraint(['pl_id'], ['packing_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pl_lineas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pl_lineas_factura_linea_id'), ['factura_linea_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pl_lineas_pl_id'), ['pl_id'], unique=False)

    op.create_table('grupo_cajas_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('pl_linea_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_por_caja', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_cajas.id'], ),
    sa.ForeignKeyConstraint(['pl_linea_id'], ['pl_lineas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grupo_cajas_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grupo_cajas_items_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grupo_cajas_items_pl_linea_id'), ['pl_linea_id'], unique=False)

    op.create_table('recepciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pl_linea_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_recibida', sa.Integer(), nullable=False),
    sa.Column('cantidad_danada', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.String(length=300), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pl_linea_id'], ['pl_lineas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pl_linea_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recepciones')
    with op.batch_alter_table('grupo_cajas_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grupo_cajas_items_pl_linea_id'))
        batch_op.drop_index(batch_op.f('ix_grupo_cajas_items_grupo_id'))

    op.drop_table('grupo_cajas_items')
    with op.batch_alter_table('pl_lineas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pl_lineas_pl_id'))
        batch_op.drop_index(batch_op.f('ix_pl_lineas_factura_linea_id'))

    op.drop_table('pl_lineas')
    with op.batch_alter_table('factura_lineas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factura_lineas_posicion_oc_id'))
        batch_op.drop_index(batch_op.f('ix_factura_lineas_factura_id'))

    op.drop_table('factura_lineas')
    with op.batch_alter_table('prepack_componentes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prepack_componentes_prepack_id'))

    op.drop_table('prepack_componentes')
    with op.batch_alter_table('posiciones_oc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posiciones_oc_oc_id'))
        batch_op.drop_index(batch_op.f('ix_posiciones_oc_articulo_id'))

    op.drop_table('posiciones_oc')
    with op.batch_alter_table('grupos_cajas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grupos_cajas_pl_id'))
        batch_op.drop_index(batch_op.f('ix_grupos_cajas_padre_id'))

    op.drop_table('grupos_cajas')
    with op.batch_alter_table('producto_versiones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_producto_versiones_producto_id'))

    op.drop_table('producto_versiones')
    with op.batch_alter_table('producto_fotos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_producto_fotos_producto_id'))

    op.drop_table('producto_fotos')
    with op.batch_alter_table('partidas_pais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partidas_pais_producto_id'))

    op.drop_table('partidas_pais')
    with op.batch_alter_table('packing_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packing_lists_unidad_carga_id'))
        batch_op.drop_index(batch_op.f('ix_packing_lists_factura_id'))
        batch_op.drop_index(batch_op.f('ix_packing_lists_estado'))

    op.drop_table('packing_lists')
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articulos_sku_proveedor'))
        batch_op.drop_index(batch_op.f('ix_articulos_producto_id'))
        batch_op.drop_index(batch_op.f('ix_articulos_marca_id'))
        batch_op.drop_index(batch_op.f('ix_articulos_grupo_id'))
        batch_op.drop_index(batch_op.f('ix_articulos_generico'))

    op.drop_table('articulos')
    with op.batch_alter_table('archivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archivos_factura_id'))

    op.drop_table('archivos')
    with op.batch_alter_table('unidades_carga', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unidades_carga_embarque_id'))

    op.drop_table('unidades_carga')
    with op.batch_alter_table('sesiones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sesiones_usuario_id'))

    op.drop_table('sesiones')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_productos_marca_id'))
        batch_op.drop_index(batch_op.f('ix_productos_estado'))
        batch_op.drop_index(batch_op.f('ix_productos_codigo_generico'))
        batch_op.drop_index(batch_op.f('ix_productos_actualizado_en'))

    op.drop_table('productos')
    with op.batch_alter_table('incisos_nacionales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incisos_nacionales_sub6'))
        batch_op.drop_index(batch_op.f('ix_incisos_nacionales_pais'))

    op.drop_table('incisos_nacionales')
    op.drop_table('importaciones_oc')
    with op.batch_alter_table('historial', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historial_fecha'))
        batch_op.drop_index(batch_op.f('ix_historial_factura_id'))

    op.drop_table('historial')
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_index('ux_factura_numero', sqlite_where=sa.text("numero IS NOT NULL AND estado <> 'CANCELADA'"), postgresql_where=sa.text("numero IS NOT NULL AND estado <> 'CANCELADA'"))
        batch_op.drop_index(batch_op.f('ix_facturas_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_facturas_estado'))

    op.drop_table('facturas')
    with op.batch_alter_table('eventos_embarque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_embarque_embarque_id'))

    op.drop_table('eventos_embarque')
    with op.batch_alter_table('desafios_dos_pasos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_desafios_dos_pasos_usuario_id'))

    op.drop_table('desafios_dos_pasos')
    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contactos_sociedad_id'))
        batch_op.drop_index(batch_op.f('ix_contactos_centro_id'))

    op.drop_table('contactos')
    op.drop_table('clasif_sinonimos')
    op.drop_table('clasif_palabras')
    op.drop_table('centro_puertos')
    op.drop_table('usuarios')
    op.drop_table('transportista_sociedades')
    op.drop_table('tipo_empaque_contiene')
    op.drop_table('proveedor_sociedades')
    op.drop_table('proveedor_marcas')
    with op.batch_alter_table('plantillas_caja', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plantillas_caja_proveedor_id'))

    op.drop_table('plantillas_caja')
    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_proveedor_id'))

    op.drop_table('ordenes_compra')
    op.drop_table('embarques')
    with op.batch_alter_table('centros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_centros_sociedad_id'))

    op.drop_table('centros')
    with op.batch_alter_table('almacenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_almacenes_sociedad_id'))

    op.drop_table('almacenes')
    op.drop_table('alertas')
    op.drop_table('transportistas')
    op.drop_table('tipos_unidad')
    op.drop_table('tipos_empaque')
    op.drop_table('sociedades')
    op.drop_table('roles')
    op.drop_table('reglas_leadtime')
    op.drop_table('regiones_leadtime')
    op.drop_table('puertos')
    op.drop_table('proveedores')
    op.drop_table('prepacks')
    op.drop_table('pasos_leadtime')
    op.drop_table('partidas_sac')
    op.drop_table('paises_arancel')
    op.drop_table('paises')
    op.drop_table('notas_sac')
    op.drop_table('meta')
    op.drop_table('marcas')
    op.drop_table('idempotencia')
    op.drop_table('grupos_articulos')
    op.drop_table('escalas_talla')
    op.drop_table('acuerdos_comerciales')
    # ### end Alembic commands ###
