"""Capa oficial: fuentes, versiones, capitulos y dominios

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 19:13:47.460167
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dominios_clasificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=400), nullable=True),
    sa.Column('modo', sa.String(length=10), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('fuentes_oficiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('ambito', sa.String(length=20), nullable=False),
    sa.Column('autoridad', sa.String(length=150), nullable=False),
    sa.Column('dataset', sa.String(length=200), nullable=False),
    sa.Column('uso', sa.String(length=300), nullable=True),
    sa.Column('url', sa.String(length=400), nullable=True),
    sa.Column('acceso', sa.String(length=60), nullable=True),
    sa.Column('autenticacion', sa.String(length=60), nullable=True),
    sa.Column('nota_version', sa.String(length=300), nullable=True),
    sa.Column('verificacion', sa.String(length=120), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('dominio_capitulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dominio_id', sa.Integer(), nullable=False),
    sa.Column('capitulo', sa.String(length=2), nullable=False),
    sa.Column('relevancia', sa.String(length=10), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.Column('proposito', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['dominio_id'], ['dominios_clasificacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dominio_id', 'capitulo')
    )
    with op.batch_alter_table('dominio_capitulos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dominio_capitulos_dominio_id'), ['dominio_id'], unique=False)

    op.create_table('versiones_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('dataset', sa.String(length=120), nullable=False),
    sa.Column('etiqueta', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=True),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.Column('fuente_id', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('nota', sa.String(length=400), nullable=True),
    sa.Column('importado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes_oficiales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('control_capitulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capitulo', sa.String(length=2), nullable=False),
    sa.Column('seccion', sa.String(length=6), nullable=True),
    sa.Column('titulo', sa.String(length=400), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('clasificacion', sa.Boolean(), nullable=False),
    sa.Column('candidato_auto', sa.Boolean(), nullable=False),
    sa.Column('solo_manual', sa.Boolean(), nullable=False),
    sa.Column('archivado', sa.Boolean(), nullable=False),
    sa.Column('alcance', sa.String(length=200), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('fuente_id', sa.Integer(), nullable=True),
    sa.Column('nota', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes_oficiales.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versiones_dataset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capitulo')
    )
    with op.batch_alter_table('paises_arancel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitudes', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('nivel_base', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('modelo_arancel', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('contexto', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('fuente_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_paises_arancel_fuente_id', 'fuentes_oficiales', ['fuente_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paises_arancel', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_paises_arancel_fuente_id', type_='foreignkey')
        batch_op.drop_column('fuente_id')
        batch_op.drop_column('contexto')
        batch_op.drop_column('modelo_arancel')
        batch_op.drop_column('nivel_base')
        batch_op.drop_column('longitudes')

    op.drop_table('control_capitulos')
    op.drop_table('versiones_dataset')
    with op.batch_alter_table('dominio_capitulos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dominio_capitulos_dominio_id'))

    op.drop_table('dominio_capitulos')
    op.drop_table('fuentes_oficiales')
    op.drop_table('dominios_clasificacion')
    # ### end Alembic commands ###
