"""Arbol arancelario versionado

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-01 19:22:53.495774
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodos_arancel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('nomenclatura', sa.String(length=10), nullable=False),
    sa.Column('pais', sa.String(length=2), nullable=True),
    sa.Column('nivel', sa.String(length=12), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('codigo_norm', sa.String(length=16), nullable=False),
    sa.Column('padre_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('texto_propio', sa.String(length=400), nullable=True),
    sa.Column('dai', sa.String(length=12), nullable=True),
    sa.Column('hojas', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=True),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.Column('fuente_id', sa.Integer(), nullable=True),
    sa.Column('nota', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes_oficiales.id'], ),
    sa.ForeignKeyConstraint(['padre_id'], ['nodos_arancel.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versiones_dataset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'pais', 'codigo_norm')
    )
    with op.batch_alter_table('nodos_arancel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nodos_arancel_codigo_norm'), ['codigo_norm'], unique=False)
        batch_op.create_index(batch_op.f('ix_nodos_arancel_version_id'), ['version_id'], unique=False)
        batch_op.create_index('ix_nodos_arancel_version_padre', ['version_id', 'padre_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodos_arancel', schema=None) as batch_op:
        batch_op.drop_index('ix_nodos_arancel_version_padre')
        batch_op.drop_index(batch_op.f('ix_nodos_arancel_version_id'))
        batch_op.drop_index(batch_op.f('ix_nodos_arancel_codigo_norm'))

    op.drop_table('nodos_arancel')
    # ### end Alembic commands ###
