"""Atributos, opciones y ámbitos de la ficha

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-01 19:32:50.320601
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atributos_def',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=200), nullable=False),
    sa.Column('tipo_dato', sa.String(length=20), nullable=False),
    sa.Column('unidad', sa.String(length=10), nullable=True),
    sa.Column('multiple', sa.Boolean(), nullable=False),
    sa.Column('usado_clasificacion', sa.Boolean(), nullable=False),
    sa.Column('dominio', sa.String(length=30), nullable=True),
    sa.Column('descripcion', sa.String(length=400), nullable=True),
    sa.Column('origen', sa.String(length=10), nullable=False),
    sa.Column('de_composicion', sa.Boolean(), nullable=False),
    sa.Column('informativo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['versiones_dataset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('atributo_ambitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atributo_id', sa.Integer(), nullable=False),
    sa.Column('tipo_ambito', sa.String(length=12), nullable=False),
    sa.Column('codigo_ambito', sa.String(length=40), nullable=False),
    sa.Column('modo', sa.String(length=8), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('condicion', sa.JSON(), nullable=True),
    sa.Column('nota', sa.String(length=300), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['atributo_id'], ['atributos_def.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atributo_id', 'tipo_ambito', 'codigo_ambito')
    )
    with op.batch_alter_table('atributo_ambitos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atributo_ambitos_atributo_id'), ['atributo_id'], unique=False)

    op.create_table('atributo_opciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atributo_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('etiqueta', sa.String(length=300), nullable=False),
    sa.Column('alias', sa.String(length=400), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['atributo_id'], ['atributos_def.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atributo_id', 'codigo')
    )
    with op.batch_alter_table('atributo_opciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atributo_opciones_atributo_id'), ['atributo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atributo_opciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atributo_opciones_atributo_id'))

    op.drop_table('atributo_opciones')
    with op.batch_alter_table('atributo_ambitos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atributo_ambitos_atributo_id'))

    op.drop_table('atributo_ambitos')
    op.drop_table('atributos_def')
    # ### end Alembic commands ###
