"""Reglas de clasificación: las condiciones de los códigos nacionales pasan a reglas

Cada código nacional con condiciones o prioridad (incisos_nacionales.cond/prio)
se convierte en una regla NATIONAL_SELECT con sus condiciones; después se
quitan esas columnas del código oficial. El downgrade las reconstruye.

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-01 19:44:52.367135
"""
import json
import secrets
from datetime import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

FUENTE = {"aprendido": "LEARNED", "manual": "MANUAL", "archivo": "NATIONAL_TARIFF", "oficial": "NATIONAL_TARIFF", "base": "LEARNED"}


def _condiciones(cond: dict) -> list[tuple]:
    out = []
    for k, v in cond.items():
        if v in (None, "", []):
            continue
        if k in ("cifMax", "cifMin"):
            out.append(("valorCIF", "LTE" if k == "cifMax" else "GT", v))
        else:
            out.append((k, "IN" if isinstance(v, list) else "EQUAL", v))
    return out


def _leer_condiciones() -> list:
    return op.get_bind().execute(sa.text("SELECT id, pais, sub6, cond, prio, fuente FROM incisos_nacionales")).fetchall()


def _mover_a_reglas(filas: list) -> None:
    """Se llama después de recrear incisos_nacionales: en SQLite el modo batch
    borra y recrea la tabla, y con claves foráneas activas eso borraría en
    cascada las reglas ya creadas."""
    con = op.get_bind()
    reglas = sa.table("reglas_clasificacion", *[sa.column(c) for c in (
        "codigo", "tipo_ambito", "codigo_ambito", "pais", "tipo_regla", "prioridad", "tipo_fuente", "familia",
        "activo", "requiere_revision", "inciso_id", "actualizado_en")])
    conds = sa.table("reglas_condiciones", sa.column("regla_id"), sa.column("grupo"), sa.column("campo"), sa.column("operador"),
                     sa.column("valor", sa.JSON), sa.column("negado", sa.Boolean))
    for iid, pais, sub6, cond, prio, fuente in filas:
        cond = json.loads(cond) if isinstance(cond, str) else (cond or {})
        lista = _condiciones(cond or {})
        if not lista and not prio:
            continue
        codigo = f"NAC-{secrets.token_hex(5).upper()}"
        con.execute(reglas.insert().values(
            codigo=codigo, tipo_ambito="NATIONAL_CODE", codigo_ambito=sub6 or "", pais=pais,
            tipo_regla="NATIONAL_SELECT", prioridad=int(prio or 0), tipo_fuente=FUENTE.get(fuente or "", "MANUAL"),
            familia="NATIONAL_CODE", activo=True, requiere_revision=False, inciso_id=iid, actualizado_en=datetime.now()))
        rid = con.execute(sa.text("SELECT id FROM reglas_clasificacion WHERE codigo = :c"), {"c": codigo}).scalar_one()
        for campo, operador, valor in lista:
            con.execute(conds.insert().values(regla_id=rid, grupo=1, campo=campo, operador=operador, valor=valor, negado=False))

revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reglas_clasificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('tipo_ambito', sa.String(length=14), nullable=False),
    sa.Column('codigo_ambito', sa.String(length=40), nullable=False),
    sa.Column('pais', sa.String(length=2), nullable=True),
    sa.Column('tipo_regla', sa.String(length=20), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('tipo_fuente', sa.String(length=20), nullable=False),
    sa.Column('familia', sa.String(length=30), nullable=True),
    sa.Column('efecto', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('requiere_revision', sa.Boolean(), nullable=False),
    sa.Column('inciso_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inciso_id'], ['incisos_nacionales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['versiones_dataset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('inciso_id')
    )
    with op.batch_alter_table('reglas_clasificacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reglas_clasificacion_pais'), ['pais'], unique=False)

    op.create_table('reglas_condiciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regla_id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(length=60), nullable=False),
    sa.Column('operador', sa.String(length=10), nullable=False),
    sa.Column('valor', sa.JSON(), nullable=True),
    sa.Column('valor_hasta', sa.JSON(), nullable=True),
    sa.Column('negado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['regla_id'], ['reglas_clasificacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reglas_condiciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reglas_condiciones_regla_id'), ['regla_id'], unique=False)

    filas = _leer_condiciones()
    with op.batch_alter_table('incisos_nacionales', schema=None) as batch_op:
        batch_op.drop_column('cond')
        batch_op.drop_column('prio')
    _mover_a_reglas(filas)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Se leen las reglas antes de recrear la tabla (ver _mover_a_reglas)
    con = op.get_bind()
    previas = []
    for rid, iid, prio in con.execute(sa.text(
            "SELECT id, inciso_id, prioridad FROM reglas_clasificacion WHERE inciso_id IS NOT NULL")).fetchall():
        cond = {}
        for campo, operador, valor in con.execute(sa.text(
                "SELECT campo, operador, valor FROM reglas_condiciones WHERE regla_id = :r"), {"r": rid}).fetchall():
            valor = json.loads(valor) if isinstance(valor, str) else valor
            cond[("cifMax" if operador == "LTE" else "cifMin") if campo == "valorCIF" else campo] = valor
        previas.append((iid, cond, prio))
    with op.batch_alter_table('incisos_nacionales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prio', sa.INTEGER(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('cond', sqlite.JSON(), nullable=False, server_default='{}'))
    for iid, cond, prio in previas:
        con.execute(sa.text("UPDATE incisos_nacionales SET cond = :c, prio = :p WHERE id = :i"),
                    {"c": json.dumps(cond), "p": prio or 0, "i": iid})

    with op.batch_alter_table('reglas_condiciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reglas_condiciones_regla_id'))

    op.drop_table('reglas_condiciones')
    with op.batch_alter_table('reglas_clasificacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reglas_clasificacion_pais'))

    op.drop_table('reglas_clasificacion')
    # ### end Alembic commands ###
