"""capa nacional regulaciones e impuestos

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-01 19:54:48.592935
"""
from alembic import op
import sqlalchemy as sa


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reglas_impuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('pais', sa.String(length=2), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('patron', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('tasa', sa.Float(), nullable=True),
    sa.Column('base_calculo', sa.String(length=80), nullable=True),
    sa.Column('umbral_desde', sa.Float(), nullable=True),
    sa.Column('umbral_hasta', sa.Float(), nullable=True),
    sa.Column('formula', sa.String(length=300), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=True),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.Column('fuente_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('base_legal', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes_oficiales.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versiones_dataset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    with op.batch_alter_table('reglas_impuesto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reglas_impuesto_pais'), ['pais'], unique=False)

    op.create_table('regulaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('pais', sa.String(length=2), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('tipo_ambito', sa.String(length=14), nullable=False),
    sa.Column('patron', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('autoridad', sa.String(length=200), nullable=True),
    sa.Column('codigo_permiso', sa.String(length=60), nullable=True),
    sa.Column('obligatorio', sa.Boolean(), nullable=False),
    sa.Column('condicion', sa.JSON(), nullable=True),
    sa.Column('base_legal', sa.String(length=400), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=True),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.Column('fuente_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('nota', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes_oficiales.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versiones_dataset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    with op.batch_alter_table('regulaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regulaciones_pais'), ['pais'], unique=False)

    with op.batch_alter_table('incisos_nacionales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_oficial', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('codigo_base', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fuente_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vigente_desde', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('vigente_hasta', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=300), nullable=True))
        batch_op.create_foreign_key('fk_incisos_fuente', 'fuentes_oficiales', ['fuente_id'], ['id'])
        batch_op.create_foreign_key('fk_incisos_version', 'versiones_dataset', ['version_id'], ['id'])

    with op.batch_alter_table('paises_arancel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuente_regulaciones_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fuente_impuestos_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ingesta', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('autenticacion_fuente', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('estado_fuente', sa.String(length=200), nullable=True))
        batch_op.create_foreign_key('fk_paises_fuente_imp', 'fuentes_oficiales', ['fuente_impuestos_id'], ['id'])
        batch_op.create_foreign_key('fk_paises_fuente_reg', 'fuentes_oficiales', ['fuente_regulaciones_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paises_arancel', schema=None) as batch_op:
        batch_op.drop_constraint('fk_paises_fuente_reg', type_='foreignkey')
        batch_op.drop_constraint('fk_paises_fuente_imp', type_='foreignkey')
        batch_op.drop_column('estado_fuente')
        batch_op.drop_column('autenticacion_fuente')
        batch_op.drop_column('ingesta')
        batch_op.drop_column('fuente_impuestos_id')
        batch_op.drop_column('fuente_regulaciones_id')

    with op.batch_alter_table('incisos_nacionales', schema=None) as batch_op:
        batch_op.drop_constraint('fk_incisos_version', type_='foreignkey')
        batch_op.drop_constraint('fk_incisos_fuente', type_='foreignkey')
        batch_op.drop_column('url')
        batch_op.drop_column('vigente_hasta')
        batch_op.drop_column('vigente_desde')
        batch_op.drop_column('fuente_id')
        batch_op.drop_column('version_id')
        batch_op.drop_column('codigo_base')
        batch_op.drop_column('codigo_oficial')

    with op.batch_alter_table('regulaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regulaciones_pais'))

    op.drop_table('regulaciones')
    with op.batch_alter_table('reglas_impuesto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reglas_impuesto_pais'))

    op.drop_table('reglas_impuesto')
    # ### end Alembic commands ###
