"""Cargas oficiales por etapas: lotes (previa) y sus diferencias

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-06 12:04:06.992245
"""
from alembic import op
import sqlalchemy as sa


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotes_oficiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archivo', sa.String(length=300), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('contenido', sa.LargeBinary(), nullable=False),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('resumen', sa.JSON(), nullable=False),
    sa.Column('errores', sa.JSON(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('publicado_en', sa.DateTime(), nullable=True),
    sa.Column('publicado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publicado_por'], ['usuarios.id'], name='fk_lotes_publicado_por'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lotes_oficiales_filas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('tabla', sa.String(length=40), nullable=False),
    sa.Column('clave', sa.String(length=120), nullable=False),
    sa.Column('accion', sa.String(length=10), nullable=False),
    sa.Column('antes', sa.JSON(), nullable=True),
    sa.Column('despues', sa.JSON(), nullable=True),
    sa.Column('advertencia', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_oficiales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lotes_oficiales_filas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lotes_oficiales_filas_lote_id'), ['lote_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes_oficiales_filas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lotes_oficiales_filas_lote_id'))

    op.drop_table('lotes_oficiales_filas')
    op.drop_table('lotes_oficiales')
    # ### end Alembic commands ###
