"""El producto guarda el HS6; la línea SAC y cada país, aparte con su evidencia

Los códigos aprobados o sugeridos de más de 6 dígitos pasan a la línea SAC
(si son de 8 o 10 dígitos) y el producto queda con su HS6.

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-06 13:41:12.144869
"""
from alembic import op
import sqlalchemy as sa


revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidas_pais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inciso_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fuente_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sugerido', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('motivo', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('aprobado_por_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('aprobado_en', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('evidencia', sa.JSON(), nullable=True))
        batch_op.create_foreign_key('fk_partidas_inciso', 'incisos_nacionales', ['inciso_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_partidas_fuente', 'fuentes_oficiales', ['fuente_id'], ['id'])
        batch_op.create_foreign_key('fk_partidas_version', 'versiones_dataset', ['version_id'], ['id'])
        batch_op.create_foreign_key('fk_partidas_aprobado_por', 'usuarios', ['aprobado_por_id'], ['id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sac_sugerido', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('sac_codigo', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('version_arancel_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('evidencia', sa.JSON(), nullable=True))
        batch_op.create_foreign_key('fk_productos_version', 'versiones_dataset', ['version_arancel_id'], ['id'])

    op.execute("UPDATE productos SET sac_codigo = codigo WHERE length(codigo) IN (8, 10)")
    op.execute("UPDATE productos SET sac_sugerido = sugerido WHERE length(sugerido) IN (8, 10)")
    op.execute("UPDATE productos SET codigo = substr(codigo, 1, 6) WHERE length(codigo) > 6")
    op.execute("UPDATE productos SET sugerido = substr(sugerido, 1, 6) WHERE length(sugerido) > 6")
    op.execute("UPDATE productos SET propuesta = substr(propuesta, 1, 6) WHERE length(propuesta) > 6")
    op.execute("UPDATE partidas_pais SET sugerido = codigo WHERE NOT manual")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("UPDATE productos SET codigo = sac_codigo WHERE sac_codigo IS NOT NULL")
    op.execute("UPDATE productos SET sugerido = sac_sugerido WHERE sac_sugerido IS NOT NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_productos_version', type_='foreignkey')
        batch_op.drop_column('evidencia')
        batch_op.drop_column('version_arancel_id')
        batch_op.drop_column('sac_codigo')
        batch_op.drop_column('sac_sugerido')

    with op.batch_alter_table('partidas_pais', schema=None) as batch_op:
        batch_op.drop_constraint('fk_partidas_aprobado_por', type_='foreignkey')
        batch_op.drop_constraint('fk_partidas_version', type_='foreignkey')
        batch_op.drop_constraint('fk_partidas_fuente', type_='foreignkey')
        batch_op.drop_constraint('fk_partidas_inciso', type_='foreignkey')
        batch_op.drop_column('evidencia')
        batch_op.drop_column('aprobado_en')
        batch_op.drop_column('aprobado_por_id')
        batch_op.drop_column('motivo')
        batch_op.drop_column('sugerido')
        batch_op.drop_column('fuente_id')
        batch_op.drop_column('version_id')
        batch_op.drop_column('inciso_id')

    # ### end Alembic commands ###
