"""Reglas ejecutables: acción de cada regla (restringir, excluir, subir, preguntar, revisar)

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-06 13:47:45.339673
"""
from alembic import op
import sqlalchemy as sa


revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reglas_clasificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accion', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reglas_clasificacion', schema=None) as batch_op:
        batch_op.drop_column('accion')

    # ### end Alembic commands ###
