"""Capa custom sobre el dato oficial; se retira partidas_sac

Las ediciones manuales de partidas/subpartidas (partidas_sac con fuente manual
o archivo) pasan a overrides sobre el árbol oficial y la tabla se elimina: el
texto SAC sale solo del árbol versionado. Las notas oficiales ganan versión,
fuente y vigencia.

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-06 14:00:18.707894
"""
from alembic import op
import sqlalchemy as sa


revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overrides_arancel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('objetivo', sa.String(length=40), nullable=False),
    sa.Column('campo', sa.String(length=30), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('valor_oficial', sa.Text(), nullable=True),
    sa.Column('motivo', sa.String(length=300), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=True),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('overrides_arancel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_overrides_arancel_objetivo'), ['objetivo'], unique=False)

    op.execute("""INSERT INTO overrides_arancel (tipo, objetivo, campo, valor, valor_oficial, motivo, creado_en, activo)
        SELECT 'NODO', p.codigo, 'descripcion', p.descripcion, n.descripcion, 'Migrated from a manual edit of the SAC text', CURRENT_TIMESTAMP, TRUE
        FROM partidas_sac p JOIN nodos_arancel n ON n.codigo_norm = p.codigo AND n.pais IS NULL
        WHERE p.fuente IN ('manual', 'archivo') AND p.descripcion <> n.descripcion""")
    op.drop_table('partidas_sac')
    with op.batch_alter_table('notas_sac', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fuente_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vigente_desde', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('vigente_hasta', sa.Date(), nullable=True))
        batch_op.create_foreign_key('fk_notas_fuente', 'fuentes_oficiales', ['fuente_id'], ['id'])
        batch_op.create_foreign_key('fk_notas_version', 'versiones_dataset', ['version_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas_sac', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notas_version', type_='foreignkey')
        batch_op.drop_constraint('fk_notas_fuente', type_='foreignkey')
        batch_op.drop_column('vigente_hasta')
        batch_op.drop_column('vigente_desde')
        batch_op.drop_column('fuente_id')
        batch_op.drop_column('version_id')

    op.create_table('partidas_sac',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=6), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=400), nullable=False),
    sa.Column('nota', sa.VARCHAR(length=300), nullable=True),
    sa.Column('fuente', sa.VARCHAR(length=12), nullable=False),
    sa.Column('activo', sa.BOOLEAN(), nullable=False),
    sa.Column('actualizado_en', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    with op.batch_alter_table('overrides_arancel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_overrides_arancel_objetivo'))

    op.drop_table('overrides_arancel')
    # ### end Alembic commands ###
