"""Categorías de producto como configuración (ya no salen del código)

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-06 14:07:19.279813
"""
from alembic import op
import sqlalchemy as sa


revision = '0011'
down_revision = '0010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('grupo', sa.String(length=80), nullable=True),
    sa.Column('dominio', sa.String(length=30), nullable=True),
    sa.Column('alias', sa.String(length=400), nullable=True),
    sa.Column('ficha_motor', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    with op.batch_alter_table('categorias_producto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_producto_dominio'), ['dominio'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias_producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_producto_dominio'))

    op.drop_table('categorias_producto')
    # ### end Alembic commands ###
