"""Comportamiento de atributos y categorias como datos

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-06 16:52:28.265143
"""
from alembic import op
import sqlalchemy as sa


revision = '0012'
down_revision = '0011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atributo_opciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bloqueo', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('implica', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('patrones', sa.JSON(), nullable=True))

    with op.batch_alter_table('atributos_def', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seccion', sa.String(length=16), nullable=False, server_default='caracteristicas'))
        batch_op.add_column(sa.Column('valor_defecto', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('derivacion', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('bloqueo', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('patrones', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('patrones_falso', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('control', sa.String(length=12), nullable=True))

    with op.batch_alter_table('categorias_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('familia', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('nombre_corto', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('nombre_aduana', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('patrones', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('capitulos', sa.JSON(), nullable=True))

    # ### end Alembic commands ###
    # El comportamiento (derivaciones, bloqueos, patrones, ámbitos exactos) lo
    # completa atributos.cargar_motor al iniciar (migraciones.actualizar).


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias_producto', schema=None) as batch_op:
        batch_op.drop_column('capitulos')
        batch_op.drop_column('patrones')
        batch_op.drop_column('nombre_aduana')
        batch_op.drop_column('nombre_corto')
        batch_op.drop_column('familia')

    with op.batch_alter_table('atributos_def', schema=None) as batch_op:
        batch_op.drop_column('control')
        batch_op.drop_column('patrones_falso')
        batch_op.drop_column('patrones')
        batch_op.drop_column('bloqueo')
        batch_op.drop_column('derivacion')
        batch_op.drop_column('valor_defecto')
        batch_op.drop_column('seccion')

    with op.batch_alter_table('atributo_opciones', schema=None) as batch_op:
        batch_op.drop_column('patrones')
        batch_op.drop_column('implica')
        batch_op.drop_column('bloqueo')

    # ### end Alembic commands ###
