"""Version por ambito y revision de reglas

Revision ID: 0013
Revises: 0012
Create Date: 2026-10-06 17:02:53.443739
"""
from alembic import op
import sqlalchemy as sa


revision = '0013'
down_revision = '0012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reglas_clasificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revision', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('nota_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reglas_nota', 'notas_sac', ['nota_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('atributo_opciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texto_aduana', sa.JSON(), nullable=True))
    with op.batch_alter_table('atributos_def', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texto_aduana', sa.JSON(), nullable=True))
    with op.batch_alter_table('categorias_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plantilla_aduana', sa.JSON(), nullable=True))

    with op.batch_alter_table('versiones_dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ambito', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_versiones_dataset_ambito'), ['ambito'], unique=False)

    # ### end Alembic commands ###
    # Datos: el ámbito de cada versión (REGIONAL o el país) y la versión de
    # cada código nacional oficial (antes no la tenía: se mezclaban versiones)
    import re

    con = op.get_bind()
    fuentes = dict(con.execute(sa.text("SELECT id, ambito FROM fuentes_oficiales")).all())
    por_pais: dict[str, list] = {}
    for vid, cod, fid, estado, desde in con.execute(sa.text("SELECT id, codigo, fuente_id, estado, vigente_desde FROM versiones_dataset")).all():
        amb = None
        f = (fuentes.get(fid) or "").strip().upper()
        if re.fullmatch(r"[A-Z]{2}", f):
            amb = f
        elif f.startswith("REGION"):
            amb = "REGIONAL"
        else:
            m = re.match(r"^([A-Z]{2})-", cod or "")
            amb = m.group(1) if m and not cod.startswith("SAC") else "REGIONAL"
        con.execute(sa.text("UPDATE versiones_dataset SET ambito = :a WHERE id = :i"), {"a": amb, "i": vid})
        if amb != "REGIONAL" and estado in ("PUBLICADA", "DINAMICA"):
            por_pais.setdefault(amb, []).append((str(desde or ""), vid))
    for iso, vs in por_pais.items():
        vid = max(vs)[1]
        con.execute(sa.text("UPDATE incisos_nacionales SET version_id = :v WHERE pais = :p AND version_id IS NULL AND fuente = 'oficial'"),
                    {"v": vid, "p": iso})


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for t, c in (("atributo_opciones", "texto_aduana"), ("atributos_def", "texto_aduana"), ("categorias_producto", "plantilla_aduana")):
        with op.batch_alter_table(t, schema=None) as batch_op:
            batch_op.drop_column(c)
    with op.batch_alter_table('versiones_dataset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_versiones_dataset_ambito'))
        batch_op.drop_column('ambito')

    with op.batch_alter_table('reglas_clasificacion', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reglas_nota', type_='foreignkey')
        batch_op.drop_column('nota_id')
        batch_op.drop_column('revision')

    # ### end Alembic commands ###
