"""Listas de valores configurables

Unidades de medida, monedas, incoterms, modos y modalidades de transporte y
tipos de centro, almacén, contacto, impuesto y documento técnico pasan de
estar fijos en el código a la tabla valores_lista (Datos maestros → Listas de
valores). Se siembran los valores que el sistema usaba hasta ahora.

Revision ID: 0040
Revises: 0039
Create Date: 2026-10-09 00:00:00
"""
from alembic import op
import sqlalchemy as sa


revision = '0040'
down_revision = '0039'
branch_labels = None
depends_on = None

VALORES = [
    {'lista': 'unidad', 'codigo': 'PAR', 'nombre': 'pair', 'orden': 1, 'activo': True, 'nombre_plural': 'pairs', 'alias': 'PR,PRS,PARES,PAIR,PAIRS', 'contable': True, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'unidad', 'codigo': 'UN', 'nombre': 'unit', 'orden': 2, 'activo': True, 'nombre_plural': 'units', 'alias': 'U,UND,UNID,UNIDAD,UNIDADES,EA,PC,PCS,PZA,PIEZA,PIEZAS,UNIT,UNITS', 'contable': True, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'unidad', 'codigo': 'DOC', 'nombre': 'dozen', 'orden': 3, 'activo': True, 'nombre_plural': 'dozens', 'alias': 'DOCENA,DOCENAS,DZ,DOZ,DOZEN', 'contable': True, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'unidad', 'codigo': 'JGO', 'nombre': 'set', 'orden': 4, 'activo': True, 'nombre_plural': 'sets', 'alias': 'JUEGO,JUEGOS,SET,SETS,KIT,KITS', 'contable': True, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'unidad', 'codigo': 'KG', 'nombre': 'kg', 'orden': 5, 'activo': True, 'nombre_plural': 'kg', 'alias': 'KGS,KILO,KILOS,KILOGRAMO,KILOGRAMOS', 'contable': False, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'unidad', 'codigo': 'G', 'nombre': 'g', 'orden': 6, 'activo': True, 'nombre_plural': 'g', 'alias': 'GR,GRS,GRAMO,GRAMOS', 'contable': False, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'unidad', 'codigo': 'L', 'nombre': 'liter', 'orden': 7, 'activo': True, 'nombre_plural': 'liters', 'alias': 'LT,LTS,LITRO,LITROS,LITER,LITERS,LITRE', 'contable': False, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'unidad', 'codigo': 'ML', 'nombre': 'ml', 'orden': 8, 'activo': True, 'nombre_plural': 'ml', 'alias': 'MILILITRO,MILILITROS', 'contable': False, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'unidad', 'codigo': 'M', 'nombre': 'meter', 'orden': 9, 'activo': True, 'nombre_plural': 'meters', 'alias': 'MT,MTS,METRO,METROS,METER,METERS', 'contable': False, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'unidad', 'codigo': 'M2', 'nombre': 'm²', 'orden': 10, 'activo': True, 'nombre_plural': 'm²', 'alias': 'MT2,MTS2,METRO2,SQM', 'contable': False, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'unidad', 'codigo': 'M3', 'nombre': 'm³', 'orden': 11, 'activo': True, 'nombre_plural': 'm³', 'alias': 'MT3,METRO3,CBM', 'contable': False, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'unidad', 'codigo': 'ROL', 'nombre': 'roll', 'orden': 12, 'activo': True, 'nombre_plural': 'rolls', 'alias': 'ROLLO,ROLLOS,ROLL,ROLLS', 'contable': True, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'unidad', 'codigo': 'CJ', 'nombre': 'prepack carton', 'orden': 13, 'activo': True, 'nombre_plural': 'prepack cartons', 'alias': 'CAJA,CAJAS,CS,CTN', 'contable': True, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'moneda', 'codigo': 'USD', 'nombre': 'US dollar', 'orden': 1, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': '$', 'decimales': 2, 'letras_en': 'US DOLLAR|US DOLLARS', 'letras_es': 'DÓLAR|DÓLARES', 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'moneda', 'codigo': 'EUR', 'nombre': 'Euro', 'orden': 2, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': '€', 'decimales': 2, 'letras_en': 'EURO|EUROS', 'letras_es': 'EURO|EUROS', 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'moneda', 'codigo': 'GTQ', 'nombre': 'Quetzal', 'orden': 3, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': 'Q', 'decimales': 2, 'letras_en': 'QUETZAL|QUETZALES', 'letras_es': 'QUETZAL|QUETZALES', 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'moneda', 'codigo': 'CRC', 'nombre': 'Colón', 'orden': 4, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': '₡', 'decimales': 2, 'letras_en': 'COLON|COLONES', 'letras_es': 'COLÓN|COLONES', 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'moneda', 'codigo': 'HNL', 'nombre': 'Lempira', 'orden': 5, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': 'L', 'decimales': 2, 'letras_en': 'LEMPIRA|LEMPIRAS', 'letras_es': 'LEMPIRA|LEMPIRAS', 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'moneda', 'codigo': 'NIO', 'nombre': 'Córdoba', 'orden': 6, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': 'C$', 'decimales': 2, 'letras_en': 'CORDOBA|CORDOBAS', 'letras_es': 'CÓRDOBA|CÓRDOBAS', 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'moneda', 'codigo': 'PAB', 'nombre': 'Balboa', 'orden': 7, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': 'B/.', 'decimales': 2, 'letras_en': 'BALBOA|BALBOAS', 'letras_es': 'BALBOA|BALBOAS', 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'moneda', 'codigo': 'MXN', 'nombre': 'Mexican peso', 'orden': 8, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': '$', 'decimales': 2, 'letras_en': 'MEXICAN PESO|MEXICAN PESOS', 'letras_es': 'PESO MEXICANO|PESOS MEXICANOS', 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'incoterm', 'codigo': 'EXW', 'nombre': 'Ex works', 'orden': 1, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'incoterm', 'codigo': 'FCA', 'nombre': 'Free carrier', 'orden': 2, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'incoterm', 'codigo': 'FAS', 'nombre': 'Free alongside ship', 'orden': 3, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'incoterm', 'codigo': 'FOB', 'nombre': 'Free on board', 'orden': 4, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'incoterm', 'codigo': 'CFR', 'nombre': 'Cost and freight', 'orden': 5, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'incoterm', 'codigo': 'CIF', 'nombre': 'Cost, insurance and freight', 'orden': 6, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'incoterm', 'codigo': 'CPT', 'nombre': 'Carriage paid to', 'orden': 7, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'incoterm', 'codigo': 'CIP', 'nombre': 'Carriage and insurance paid to', 'orden': 8, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'incoterm', 'codigo': 'DAP', 'nombre': 'Delivered at place', 'orden': 9, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'incoterm', 'codigo': 'DPU', 'nombre': 'Delivered at place unloaded', 'orden': 10, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'incoterm', 'codigo': 'DDP', 'nombre': 'Delivered duty paid', 'orden': 11, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'modo_transporte', 'codigo': 'MARITIMO', 'nombre': 'Ocean', 'orden': 1, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': 'VOLUMEN', 'factor': None, 'icono': 'barco', 'documento': 'B/L', 'etiqueta_puerto': 'Port', 'etiqueta_transportista': 'Shipping line', 'etiqueta_unidad': 'Container|Containers', 'padre': None, 'consolidado': None},
    {'lista': 'modo_transporte', 'codigo': 'AEREO', 'nombre': 'Air', 'orden': 2, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': 'PESO_COBRABLE', 'factor': 167, 'icono': 'avion', 'documento': 'AWB', 'etiqueta_puerto': 'Airport', 'etiqueta_transportista': 'Airline', 'etiqueta_unidad': 'Air waybill|Air waybills', 'padre': None, 'consolidado': None},
    {'lista': 'modo_transporte', 'codigo': 'TERRESTRE', 'nombre': 'Road', 'orden': 3, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': 'VOLUMEN', 'factor': None, 'icono': 'camion', 'documento': 'Waybill', 'etiqueta_puerto': 'Customs post', 'etiqueta_transportista': 'Carrier', 'etiqueta_unidad': 'Truck|Trucks', 'padre': None, 'consolidado': None},
    {'lista': 'modalidad_transporte', 'codigo': 'FCL', 'nombre': 'FCL · full container', 'orden': 1, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': 'MARITIMO', 'consolidado': False},
    {'lista': 'modalidad_transporte', 'codigo': 'LCL', 'nombre': 'LCL · consolidated cargo', 'orden': 2, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': 'MARITIMO', 'consolidado': True},
    {'lista': 'modalidad_transporte', 'codigo': 'AEREO', 'nombre': 'Air cargo', 'orden': 3, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': 'AEREO', 'consolidado': False},
    {'lista': 'modalidad_transporte', 'codigo': 'FTL', 'nombre': 'FTL · full truck', 'orden': 4, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': 'TERRESTRE', 'consolidado': False},
    {'lista': 'modalidad_transporte', 'codigo': 'LTL', 'nombre': 'LTL · partial load', 'orden': 5, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': 'TERRESTRE', 'consolidado': True},
    {'lista': 'tipo_centro', 'codigo': 'BODEGA_FISCAL', 'nombre': 'Bonded warehouse', 'orden': 1, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_centro', 'codigo': 'ZONA_FRANCA', 'nombre': 'Free trade zone', 'orden': 2, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_centro', 'codigo': 'LOCAL', 'nombre': 'Local warehouse', 'orden': 3, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_centro', 'codigo': 'TIENDA', 'nombre': 'Store / DC', 'orden': 4, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_almacen', 'codigo': 'VIRTUAL', 'nombre': 'Virtual', 'orden': 1, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_almacen', 'codigo': 'DETALLE', 'nombre': 'Retail', 'orden': 2, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_almacen', 'codigo': 'MAYOREO', 'nombre': 'Wholesale', 'orden': 3, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_contacto', 'codigo': 'FACTURACION', 'nombre': 'Billing', 'orden': 1, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_contacto', 'codigo': 'NOTIFY', 'nombre': 'Notify party', 'orden': 2, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_contacto', 'codigo': 'LOGISTICA', 'nombre': 'Logistics', 'orden': 3, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_impuesto', 'codigo': 'DAI', 'nombre': 'DAI', 'orden': 1, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_impuesto', 'codigo': 'IVA', 'nombre': 'IVA', 'orden': 2, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_impuesto', 'codigo': 'ITBMS', 'nombre': 'ITBMS', 'orden': 3, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_impuesto', 'codigo': 'ISV', 'nombre': 'ISV', 'orden': 4, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_impuesto', 'codigo': 'ISC', 'nombre': 'ISC', 'orden': 5, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_impuesto', 'codigo': 'SELECTIVO', 'nombre': 'SELECTIVO', 'orden': 6, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_impuesto', 'codigo': 'OTRO', 'nombre': 'Other', 'orden': 7, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_documento', 'codigo': 'SDS', 'nombre': 'SDS · safety data sheet', 'orden': 1, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_documento', 'codigo': 'TDS', 'nombre': 'TDS · technical data sheet', 'orden': 2, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
    {'lista': 'tipo_documento', 'codigo': 'COA', 'nombre': 'COA · certificate of analysis', 'orden': 3, 'activo': True, 'nombre_plural': None, 'alias': None, 'contable': None, 'simbolo': None, 'decimales': None, 'letras_en': None, 'letras_es': None, 'calculo': None, 'factor': None, 'icono': None, 'documento': None, 'etiqueta_puerto': None, 'etiqueta_transportista': None, 'etiqueta_unidad': None, 'padre': None, 'consolidado': None},
]


def upgrade() -> None:
    tabla = op.create_table(
        "valores_lista",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("lista", sa.String(30), nullable=False),
        sa.Column("codigo", sa.String(20), nullable=False),
        sa.Column("nombre", sa.String(120), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("nombre_plural", sa.String(120), nullable=True),
        sa.Column("alias", sa.String(300), nullable=True),
        sa.Column("contable", sa.Boolean(), nullable=True),
        sa.Column("simbolo", sa.String(5), nullable=True),
        sa.Column("decimales", sa.Integer(), nullable=True),
        sa.Column("letras_en", sa.String(120), nullable=True),
        sa.Column("letras_es", sa.String(120), nullable=True),
        sa.Column("calculo", sa.String(20), nullable=True),
        sa.Column("factor", sa.Float(), nullable=True),
        sa.Column("icono", sa.String(20), nullable=True),
        sa.Column("documento", sa.String(40), nullable=True),
        sa.Column("etiqueta_puerto", sa.String(40), nullable=True),
        sa.Column("etiqueta_transportista", sa.String(40), nullable=True),
        sa.Column("etiqueta_unidad", sa.String(80), nullable=True),
        sa.Column("padre", sa.String(20), nullable=True),
        sa.Column("consolidado", sa.Boolean(), nullable=True),
        sa.UniqueConstraint("lista", "codigo", name="uq_valores_lista_lista_codigo"),
    )
    op.create_index("ix_valores_lista_lista", "valores_lista", ["lista"])
    op.bulk_insert(tabla, VALORES)
    # El tipo de documento técnico es un código de la lista (antes solo SDS/TDS/COA)
    with op.batch_alter_table("producto_documentos") as b:
        b.alter_column("tipo", existing_type=sa.String(4), type_=sa.String(20), existing_nullable=False)


def downgrade() -> None:
    with op.batch_alter_table("producto_documentos") as b:
        b.alter_column("tipo", existing_type=sa.String(20), type_=sa.String(4), existing_nullable=False)
    op.drop_index("ix_valores_lista_lista", table_name="valores_lista")
    op.drop_table("valores_lista")
