"""Índices de los filtros frecuentes y permiso para ver facturas

- Índices en las columnas por las que se filtran y ordenan las listas
  (órdenes, facturas, embarques, alertas, artículos, usuarios) y en la
  bitácora por registro (entidad, entidad_id).
- Nuevo permiso `factura.ver`. Antes cualquier usuario veía las facturas y
  listas de empaque de su alcance; ahora hace falta este permiso. Se da a los
  roles que ya trabajaban con OCs, facturas o listas de empaque, para que nadie
  pierda acceso al actualizar.

Revision ID: 0046
Revises: 0045
Create Date: 2026-10-09 00:00:00
"""
from alembic import op
import sqlalchemy as sa


revision = '0046'
down_revision = '0045'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alertas_proveedor_id'), ['proveedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertas_resuelta'), ['resuelta'], unique=False)

    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articulos_proveedor_id'), ['proveedor_id'], unique=False)

    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embarques_centro'), ['centro'], unique=False)
        batch_op.create_index(batch_op.f('ix_embarques_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_embarques_etd'), ['etd'], unique=False)
        batch_op.create_index(batch_op.f('ix_embarques_transportista_id'), ['transportista_id'], unique=False)

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facturas_actualizado_en'), ['actualizado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_sociedad'), ['sociedad'], unique=False)

    with op.batch_alter_table('historial', schema=None) as batch_op:
        batch_op.create_index('ix_historial_entidad', ['entidad', 'entidad_id'], unique=False)

    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordenes_compra_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordenes_compra_liberada'), ['liberada'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordenes_compra_sociedad'), ['sociedad'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_rol_id'), ['rol_id'], unique=False)

    # ### end Alembic commands ###

    roles = sa.table("roles", sa.column("id", sa.Integer), sa.column("permisos", sa.JSON))
    con = op.get_bind()
    for rid, permisos in con.execute(sa.select(roles.c.id, roles.c.permisos)).all():
        permisos = list(permisos or [])
        if "factura.ver" not in permisos and set(permisos) & {"oc.ver", "factura.editar", "pl.editar"}:
            con.execute(roles.update().where(roles.c.id == rid).values(permisos=[*permisos, "factura.ver"]))


def downgrade() -> None:
    roles = sa.table("roles", sa.column("id", sa.Integer), sa.column("permisos", sa.JSON))
    con = op.get_bind()
    for rid, permisos in con.execute(sa.select(roles.c.id, roles.c.permisos)).all():
        if "factura.ver" in (permisos or []):
            con.execute(roles.update().where(roles.c.id == rid).values(permisos=[p for p in permisos if p != "factura.ver"]))
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_rol_id'))

    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_sociedad'))
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_liberada'))
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_fecha'))

    with op.batch_alter_table('historial', schema=None) as batch_op:
        batch_op.drop_index('ix_historial_entidad')

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facturas_sociedad'))
        batch_op.drop_index(batch_op.f('ix_facturas_actualizado_en'))

    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embarques_transportista_id'))
        batch_op.drop_index(batch_op.f('ix_embarques_etd'))
        batch_op.drop_index(batch_op.f('ix_embarques_estado'))
        batch_op.drop_index(batch_op.f('ix_embarques_centro'))

    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articulos_proveedor_id'))

    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alertas_resuelta'))
        batch_op.drop_index(batch_op.f('ix_alertas_proveedor_id'))

    # ### end Alembic commands ###
