"""Ciclo de vida de la orden de compra

- ordenes_compra: estado del documento (BORRADOR, EN_APROBACION, RECHAZADA,
  APROBADA, CERRADA, CANCELADA; las existentes quedan APROBADA), origen (ERP o
  PLATAFORMA), versión, condición de pago, notas, borrador del asistente y
  fechas de envío, aprobación y cierre.
- aprobaciones_oc: los pasos de aprobación de cada OC (con RLS en PostgreSQL,
  como las demás tablas de una organización).
- Lista de valores «condicion_pago» con sus valores de fábrica en cada
  organización.
- Permisos oc.editar, oc.aprobar y oc.cancelar para los roles que ya cargaban
  OCs (oc.importar), así nadie pierde lo que hacía.

Revision ID: 0048
Revises: 0047
Create Date: 2026-10-09 00:00:00
"""
from alembic import op
import sqlalchemy as sa


revision = '0048'
down_revision = '0047'
branch_labels = None
depends_on = None

# Igual que core/listas.FABRICA["condicion_pago"] (fijo aquí: una migración no cambia)
CONDICIONES = [("ANTICIPO", "Cash in advance", "PREPAID,CIA,CONTADO,ANTICIPADO"),
               ("NETO30", "Net 30 days", "NET30,N30,30 DIAS,30 DAYS"),
               ("NETO60", "Net 60 days", "NET60,N60,60 DIAS,60 DAYS"),
               ("NETO90", "Net 90 days", "NET90,N90,90 DIAS,90 DAYS"),
               ("CARTA_CREDITO", "Letter of credit", "LC,L/C,CARTA DE CREDITO"),
               ("CAD", "Cash against documents", "CONTRA DOCUMENTOS,D/P")]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aprobaciones_oc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oc_id', sa.Integer(), nullable=False),
    sa.Column('paso', sa.Integer(), nullable=False),
    sa.Column('regla', sa.String(length=80), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('comentario', sa.String(length=500), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oc_id'], ['ordenes_compra.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aprobaciones_oc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aprobaciones_oc_oc_id'), ['oc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aprobaciones_oc_organizacion_id'), ['organizacion_id'], unique=False)

    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), server_default='APROBADA', nullable=False))
        batch_op.add_column(sa.Column('origen', sa.String(length=12), server_default='ERP', nullable=False))
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('condicion_pago', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('borrador', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('creada_por', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('enviada_en', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aprobada_en', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cerrada_en', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('motivo_estado', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_ordenes_compra_estado'), ['estado'], unique=False)
        batch_op.create_foreign_key('fk_ordenes_compra_creada_por_usuarios', 'usuarios', ['creada_por'], ['id'])

    # ### end Alembic commands ###
    con = op.get_bind()
    if con.dialect.name == "postgresql":
        condicion = ("coalesce(current_setting('app.organizacion_id', true), '') = '' "
                     "OR organizacion_id = nullif(current_setting('app.organizacion_id', true), '')::integer")
        op.execute("ALTER TABLE aprobaciones_oc ENABLE ROW LEVEL SECURITY; ALTER TABLE aprobaciones_oc FORCE ROW LEVEL SECURITY; "
                   f"CREATE POLICY aislamiento_organizacion ON aprobaciones_oc USING ({condicion}) WITH CHECK ({condicion})")
    # Condiciones de pago de fábrica en cada organización
    valores = sa.table("valores_lista", sa.column("lista", sa.String), sa.column("codigo", sa.String),
                       sa.column("nombre", sa.String), sa.column("orden", sa.Integer), sa.column("activo", sa.Boolean),
                       sa.column("alias", sa.String), sa.column("organizacion_id", sa.Integer))
    for (org,) in con.execute(sa.text("SELECT id FROM organizaciones")).all():
        if not con.execute(sa.text("SELECT 1 FROM valores_lista WHERE lista = 'condicion_pago' AND organizacion_id = :o"),
                           {"o": org}).first():
            op.bulk_insert(valores, [dict(lista="condicion_pago", codigo=c, nombre=n, orden=i, activo=True, alias=a,
                                          organizacion_id=org) for i, (c, n, a) in enumerate(CONDICIONES, start=1)])
    roles = sa.table("roles", sa.column("id", sa.Integer), sa.column("permisos", sa.JSON))
    for rid, permisos in con.execute(sa.select(roles.c.id, roles.c.permisos)).all():
        permisos = list(permisos or [])
        if "oc.importar" in permisos:
            nuevos = [p for p in ("oc.editar", "oc.aprobar", "oc.cancelar") if p not in permisos]
            if nuevos:
                con.execute(roles.update().where(roles.c.id == rid).values(permisos=permisos + nuevos))


def downgrade() -> None:
    con = op.get_bind()
    roles = sa.table("roles", sa.column("id", sa.Integer), sa.column("permisos", sa.JSON))
    for rid, permisos in con.execute(sa.select(roles.c.id, roles.c.permisos)).all():
        quitar = {"oc.editar", "oc.aprobar", "oc.cancelar"}
        if set(permisos or []) & quitar:
            con.execute(roles.update().where(roles.c.id == rid).values(permisos=[p for p in permisos if p not in quitar]))
    con.execute(sa.text("DELETE FROM valores_lista WHERE lista = 'condicion_pago'"))
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ordenes_compra_creada_por_usuarios', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_estado'))
        batch_op.drop_column('motivo_estado')
        batch_op.drop_column('cerrada_en')
        batch_op.drop_column('aprobada_en')
        batch_op.drop_column('enviada_en')
        batch_op.drop_column('creada_por')
        batch_op.drop_column('borrador')
        batch_op.drop_column('notas')
        batch_op.drop_column('condicion_pago')
        batch_op.drop_column('version')
        batch_op.drop_column('origen')
        batch_op.drop_column('estado')

    with op.batch_alter_table('aprobaciones_oc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aprobaciones_oc_organizacion_id'))
        batch_op.drop_index(batch_op.f('ix_aprobaciones_oc_oc_id'))

    op.drop_table('aprobaciones_oc')
    # ### end Alembic commands ###
