"""Reportes guardados del generador de reportes

- reportes: nombre, tipo (operativo o analítico), definición (fuente,
  columnas, filtros, agrupación, medidas y orden), si se comparte con la
  organización y quién lo creó. Con RLS en PostgreSQL, como las demás tablas
  de una organización.

Revision ID: 0050
Revises: 0049
Create Date: 2026-10-09 00:00:00
"""
from alembic import op
import sqlalchemy as sa


revision = '0050'
down_revision = '0049'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('definicion', sa.JSON(), nullable=False),
    sa.Column('compartido', sa.Boolean(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacion_id', 'creado_por', 'nombre', name='uq_reportes_org_autor_nombre')
    )
    with op.batch_alter_table('reportes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reportes_creado_por'), ['creado_por'], unique=False)
        batch_op.create_index(batch_op.f('ix_reportes_organizacion_id'), ['organizacion_id'], unique=False)

    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        condicion = ("coalesce(current_setting('app.organizacion_id', true), '') = '' "
                     "OR organizacion_id = nullif(current_setting('app.organizacion_id', true), '')::integer")
        op.execute("ALTER TABLE reportes ENABLE ROW LEVEL SECURITY; ALTER TABLE reportes FORCE ROW LEVEL SECURITY; "
                   f"CREATE POLICY aislamiento_organizacion ON reportes USING ({condicion}) WITH CHECK ({condicion})")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reportes_organizacion_id'))
        batch_op.drop_index(batch_op.f('ix_reportes_creado_por'))

    op.drop_table('reportes')
    # ### end Alembic commands ###
